name: minimal android ci workflow

on:
  push:
    branches:
      - android
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu  # supported distrubution https://github.com/actions/setup-java#supported-distributions
          java-version: 1.8   # 11
          java-package: jdk   # jdk (default), jre  https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md

      - name: Run Tests
        run: bash ./gradlew test --stacktrace

  gen-apk:
    name: Generate APK
    needs: run-unit-test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 1.8
          java-package: jdk

      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 

  release:
    name: Release APK
    needs: gen-apk
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:

      - name: Download APK from build
        uses: actions/download-artifact@v2
        with:
          name: apk
      
      - name: display structured of downloaded files
        run: ls -R

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}

      # - name: Upload Release APK
      #   id: upload_release_asset
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: apk/app-debug.apk
      #     asset_name: MensaApp.apk
      #     asset_content_type: application/zip